 nolabels:true$
 display2d:false$
 set_plot_option([run_viewer, false])$
 set_tex_environment_default("","")$
 lbrace:"{"$
 rbrace:"}"$
 file_output_append:false$
 with_stdout("main.mxp")$
 file_output_append:true$ 

with_stdout("main.mxp", print("\\gdef\\mxpi",lbrace),
eq1:4*x^2+6*x+3,
eq2:a*x+b,
eq3:expand(eq1*eq2),
tex(eq3)

,print(rbrace))$

with_stdout("main.mxp", print("\\gdef\\mxpii",lbrace),
indexpower(equ,var):= hipow(equ,var),
powers(poly,var):= reverse(create_list(i,i,0,indexpower(poly,var))),
polycoeff(poly,var):=map(lambda([i],coeff(poly,x,i)),powers(poly,var)),
systemeq(eq,var,list):=map("=",polycoeff(eq,var),list),
printfunc(i):=print(concat(tex1(i),"\\\\")),
map(printfunc,systemeq(eq3,x,[0,0,0,1]))

,print(rbrace))$

with_stdout("main.mxp", print("\\gdef\\mxpiii",lbrace),
tex(eq1)
,print(rbrace))$

with_stdout("main.mxp", print("\\gdef\\mxpiv",lbrace),
f:expand((a+b*%i)*(c+d*%i)),     /* Integrating it */
tex(realpart(f)),
print("+"),
tex(imagpart(f)*i)

,print(rbrace))$

with_stdout("main.mxp", print("\\gdef\\mxpv",lbrace),
ar1:[realpart(f)=0,imagpart(f)=1],
map(printfunc,ar1)
,print(rbrace))$

with_stdout("main.mxp", print("\\gdef\\mxpvi",lbrace),
l1:[realpart(f)=1,imagpart(f)=0],
sol:solve(l1,[a,b,c,d]),
for i : 1 thru length (%rnum_list) do(
sol : subst (t[i], %rnum_list[i], sol)),
map(printfunc,sol[1])

,print(rbrace))$

with_stdout("main.mxp", print("\\gdef\\mxpvii",lbrace),
map(printfunc,sol[2])
,print(rbrace))$

with_stdout("main.mxp", print("\\gdef\\mxpviii",lbrace),
map(printfunc,sol[3])
,print(rbrace))$
